/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedWorkoutHistoryRouteImport } from './routes/_authenticated/workout-history'
import { Route as AuthenticatedWeightHistoryRouteImport } from './routes/_authenticated/weight-history'
import { Route as AuthenticatedWeightRouteImport } from './routes/_authenticated/weight'
import { Route as AuthenticatedSocialRouteImport } from './routes/_authenticated/social'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNutritionRouteImport } from './routes/_authenticated/nutrition'
import { Route as AuthenticatedMealPlannerRouteImport } from './routes/_authenticated/meal-planner'
import { Route as AuthenticatedFitnessRouteImport } from './routes/_authenticated/fitness'
import { Route as AuthenticatedFastingRouteImport } from './routes/_authenticated/fasting'
import { Route as AuthenticatedBadgesRouteImport } from './routes/_authenticated/badges'
import { Route as AuthenticatedAiCoachRouteImport } from './routes/_authenticated/ai-coach'
import { Route as AuthenticatedActivityHistoryRouteImport } from './routes/_authenticated/activity-history'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiAdminGenerateExerciseFramesRouteImport } from './routes/api/admin/generate-exercise-frames'
import { Route as ApiAdminBootstrapAdminRouteImport } from './routes/api/admin/bootstrap-admin'
import { Route as AuthenticatedWorkoutSessionTemplateIdRouteImport } from './routes/_authenticated/workout-session.$templateId'
import { Route as AuthenticatedAiCoachThreadIdRouteImport } from './routes/_authenticated/ai-coach.$threadId'
import { Route as AuthenticatedAdminExerciseFramesRouteImport } from './routes/_authenticated/admin.exercise-frames'
import { Route as AuthenticatedAdminEditRouteImport } from './routes/_authenticated/admin.edit'
import { Route as AuthenticatedActivitySessionActivityIdRouteImport } from './routes/_authenticated/activity-session.$activityId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicWidgetAuraRouteImport } from './routes/api/public/widget/aura'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksSendRemindersRouteImport } from './routes/api/public/hooks/send-reminders'
import { Route as ApiPublicHooksSendAuraTipsRouteImport } from './routes/api/public/hooks/send-aura-tips'
import { Route as ApiExerciseFrameIdIRouteImport } from './routes/api/exercise-frame.$id.$i'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkoutHistoryRoute =
  AuthenticatedWorkoutHistoryRouteImport.update({
    id: '/workout-history',
    path: '/workout-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWeightHistoryRoute =
  AuthenticatedWeightHistoryRouteImport.update({
    id: '/weight-history',
    path: '/weight-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWeightRoute = AuthenticatedWeightRouteImport.update({
  id: '/weight',
  path: '/weight',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSocialRoute = AuthenticatedSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNutritionRoute = AuthenticatedNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMealPlannerRoute =
  AuthenticatedMealPlannerRouteImport.update({
    id: '/meal-planner',
    path: '/meal-planner',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFitnessRoute = AuthenticatedFitnessRouteImport.update({
  id: '/fitness',
  path: '/fitness',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFastingRoute = AuthenticatedFastingRouteImport.update({
  id: '/fasting',
  path: '/fasting',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBadgesRoute = AuthenticatedBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiCoachRoute = AuthenticatedAiCoachRouteImport.update({
  id: '/ai-coach',
  path: '/ai-coach',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityHistoryRoute =
  AuthenticatedActivityHistoryRouteImport.update({
    id: '/activity-history',
    path: '/activity-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminGenerateExerciseFramesRoute =
  ApiAdminGenerateExerciseFramesRouteImport.update({
    id: '/api/admin/generate-exercise-frames',
    path: '/api/admin/generate-exercise-frames',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminBootstrapAdminRoute = ApiAdminBootstrapAdminRouteImport.update({
  id: '/api/admin/bootstrap-admin',
  path: '/api/admin/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkoutSessionTemplateIdRoute =
  AuthenticatedWorkoutSessionTemplateIdRouteImport.update({
    id: '/workout-session/$templateId',
    path: '/workout-session/$templateId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiCoachThreadIdRoute =
  AuthenticatedAiCoachThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedAiCoachRoute,
  } as any)
const AuthenticatedAdminExerciseFramesRoute =
  AuthenticatedAdminExerciseFramesRouteImport.update({
    id: '/admin/exercise-frames',
    path: '/admin/exercise-frames',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminEditRoute = AuthenticatedAdminEditRouteImport.update({
  id: '/admin/edit',
  path: '/admin/edit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivitySessionActivityIdRoute =
  AuthenticatedActivitySessionActivityIdRouteImport.update({
    id: '/activity-session/$activityId',
    path: '/activity-session/$activityId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWidgetAuraRoute = ApiPublicWidgetAuraRouteImport.update({
  id: '/api/public/widget/aura',
  path: '/api/public/widget/aura',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendRemindersRoute =
  ApiPublicHooksSendRemindersRouteImport.update({
    id: '/api/public/hooks/send-reminders',
    path: '/api/public/hooks/send-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendAuraTipsRoute =
  ApiPublicHooksSendAuraTipsRouteImport.update({
    id: '/api/public/hooks/send-aura-tips',
    path: '/api/public/hooks/send-aura-tips',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiExerciseFrameIdIRoute = ApiExerciseFrameIdIRouteImport.update({
  id: '/api/exercise-frame/$id/$i',
  path: '/api/exercise-frame/$id/$i',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/intro': typeof IntroRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/register': typeof RegisterRoute
  '/welcome': typeof WelcomeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/activity-history': typeof AuthenticatedActivityHistoryRoute
  '/ai-coach': typeof AuthenticatedAiCoachRouteWithChildren
  '/badges': typeof AuthenticatedBadgesRoute
  '/fasting': typeof AuthenticatedFastingRoute
  '/fitness': typeof AuthenticatedFitnessRoute
  '/meal-planner': typeof AuthenticatedMealPlannerRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/social': typeof AuthenticatedSocialRoute
  '/weight': typeof AuthenticatedWeightRoute
  '/weight-history': typeof AuthenticatedWeightHistoryRoute
  '/workout-history': typeof AuthenticatedWorkoutHistoryRoute
  '/api/chat': typeof ApiChatRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/activity-session/$activityId': typeof AuthenticatedActivitySessionActivityIdRoute
  '/admin/edit': typeof AuthenticatedAdminEditRoute
  '/admin/exercise-frames': typeof AuthenticatedAdminExerciseFramesRoute
  '/ai-coach/$threadId': typeof AuthenticatedAiCoachThreadIdRoute
  '/workout-session/$templateId': typeof AuthenticatedWorkoutSessionTemplateIdRoute
  '/api/admin/bootstrap-admin': typeof ApiAdminBootstrapAdminRoute
  '/api/admin/generate-exercise-frames': typeof ApiAdminGenerateExerciseFramesRoute
  '/api/exercise-frame/$id/$i': typeof ApiExerciseFrameIdIRoute
  '/api/public/hooks/send-aura-tips': typeof ApiPublicHooksSendAuraTipsRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/widget/aura': typeof ApiPublicWidgetAuraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/intro': typeof IntroRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/register': typeof RegisterRoute
  '/welcome': typeof WelcomeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/activity-history': typeof AuthenticatedActivityHistoryRoute
  '/ai-coach': typeof AuthenticatedAiCoachRouteWithChildren
  '/badges': typeof AuthenticatedBadgesRoute
  '/fasting': typeof AuthenticatedFastingRoute
  '/fitness': typeof AuthenticatedFitnessRoute
  '/meal-planner': typeof AuthenticatedMealPlannerRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/social': typeof AuthenticatedSocialRoute
  '/weight': typeof AuthenticatedWeightRoute
  '/weight-history': typeof AuthenticatedWeightHistoryRoute
  '/workout-history': typeof AuthenticatedWorkoutHistoryRoute
  '/api/chat': typeof ApiChatRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/activity-session/$activityId': typeof AuthenticatedActivitySessionActivityIdRoute
  '/admin/edit': typeof AuthenticatedAdminEditRoute
  '/admin/exercise-frames': typeof AuthenticatedAdminExerciseFramesRoute
  '/ai-coach/$threadId': typeof AuthenticatedAiCoachThreadIdRoute
  '/workout-session/$templateId': typeof AuthenticatedWorkoutSessionTemplateIdRoute
  '/api/admin/bootstrap-admin': typeof ApiAdminBootstrapAdminRoute
  '/api/admin/generate-exercise-frames': typeof ApiAdminGenerateExerciseFramesRoute
  '/api/exercise-frame/$id/$i': typeof ApiExerciseFrameIdIRoute
  '/api/public/hooks/send-aura-tips': typeof ApiPublicHooksSendAuraTipsRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/widget/aura': typeof ApiPublicWidgetAuraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/intro': typeof IntroRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/register': typeof RegisterRoute
  '/welcome': typeof WelcomeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/activity-history': typeof AuthenticatedActivityHistoryRoute
  '/_authenticated/ai-coach': typeof AuthenticatedAiCoachRouteWithChildren
  '/_authenticated/badges': typeof AuthenticatedBadgesRoute
  '/_authenticated/fasting': typeof AuthenticatedFastingRoute
  '/_authenticated/fitness': typeof AuthenticatedFitnessRoute
  '/_authenticated/meal-planner': typeof AuthenticatedMealPlannerRoute
  '/_authenticated/nutrition': typeof AuthenticatedNutritionRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/social': typeof AuthenticatedSocialRoute
  '/_authenticated/weight': typeof AuthenticatedWeightRoute
  '/_authenticated/weight-history': typeof AuthenticatedWeightHistoryRoute
  '/_authenticated/workout-history': typeof AuthenticatedWorkoutHistoryRoute
  '/api/chat': typeof ApiChatRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/activity-session/$activityId': typeof AuthenticatedActivitySessionActivityIdRoute
  '/_authenticated/admin/edit': typeof AuthenticatedAdminEditRoute
  '/_authenticated/admin/exercise-frames': typeof AuthenticatedAdminExerciseFramesRoute
  '/_authenticated/ai-coach/$threadId': typeof AuthenticatedAiCoachThreadIdRoute
  '/_authenticated/workout-session/$templateId': typeof AuthenticatedWorkoutSessionTemplateIdRoute
  '/api/admin/bootstrap-admin': typeof ApiAdminBootstrapAdminRoute
  '/api/admin/generate-exercise-frames': typeof ApiAdminGenerateExerciseFramesRoute
  '/api/exercise-frame/$id/$i': typeof ApiExerciseFrameIdIRoute
  '/api/public/hooks/send-aura-tips': typeof ApiPublicHooksSendAuraTipsRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/widget/aura': typeof ApiPublicWidgetAuraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/intro'
    | '/login'
    | '/mcp'
    | '/register'
    | '/welcome'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/activity-history'
    | '/ai-coach'
    | '/badges'
    | '/fasting'
    | '/fitness'
    | '/meal-planner'
    | '/nutrition'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/settings'
    | '/social'
    | '/weight'
    | '/weight-history'
    | '/workout-history'
    | '/api/chat'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/activity-session/$activityId'
    | '/admin/edit'
    | '/admin/exercise-frames'
    | '/ai-coach/$threadId'
    | '/workout-session/$templateId'
    | '/api/admin/bootstrap-admin'
    | '/api/admin/generate-exercise-frames'
    | '/api/exercise-frame/$id/$i'
    | '/api/public/hooks/send-aura-tips'
    | '/api/public/hooks/send-reminders'
    | '/api/public/payments/webhook'
    | '/api/public/widget/aura'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/intro'
    | '/login'
    | '/mcp'
    | '/register'
    | '/welcome'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/activity-history'
    | '/ai-coach'
    | '/badges'
    | '/fasting'
    | '/fitness'
    | '/meal-planner'
    | '/nutrition'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/settings'
    | '/social'
    | '/weight'
    | '/weight-history'
    | '/workout-history'
    | '/api/chat'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/activity-session/$activityId'
    | '/admin/edit'
    | '/admin/exercise-frames'
    | '/ai-coach/$threadId'
    | '/workout-session/$templateId'
    | '/api/admin/bootstrap-admin'
    | '/api/admin/generate-exercise-frames'
    | '/api/exercise-frame/$id/$i'
    | '/api/public/hooks/send-aura-tips'
    | '/api/public/hooks/send-reminders'
    | '/api/public/payments/webhook'
    | '/api/public/widget/aura'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/intro'
    | '/login'
    | '/mcp'
    | '/register'
    | '/welcome'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/activity-history'
    | '/_authenticated/ai-coach'
    | '/_authenticated/badges'
    | '/_authenticated/fasting'
    | '/_authenticated/fitness'
    | '/_authenticated/meal-planner'
    | '/_authenticated/nutrition'
    | '/_authenticated/onboarding'
    | '/_authenticated/pricing'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/social'
    | '/_authenticated/weight'
    | '/_authenticated/weight-history'
    | '/_authenticated/workout-history'
    | '/api/chat'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/activity-session/$activityId'
    | '/_authenticated/admin/edit'
    | '/_authenticated/admin/exercise-frames'
    | '/_authenticated/ai-coach/$threadId'
    | '/_authenticated/workout-session/$templateId'
    | '/api/admin/bootstrap-admin'
    | '/api/admin/generate-exercise-frames'
    | '/api/exercise-frame/$id/$i'
    | '/api/public/hooks/send-aura-tips'
    | '/api/public/hooks/send-reminders'
    | '/api/public/payments/webhook'
    | '/api/public/widget/aura'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  IntroRoute: typeof IntroRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  RegisterRoute: typeof RegisterRoute
  WelcomeRoute: typeof WelcomeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiAdminBootstrapAdminRoute: typeof ApiAdminBootstrapAdminRoute
  ApiAdminGenerateExerciseFramesRoute: typeof ApiAdminGenerateExerciseFramesRoute
  ApiExerciseFrameIdIRoute: typeof ApiExerciseFrameIdIRoute
  ApiPublicHooksSendAuraTipsRoute: typeof ApiPublicHooksSendAuraTipsRoute
  ApiPublicHooksSendRemindersRoute: typeof ApiPublicHooksSendRemindersRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicWidgetAuraRoute: typeof ApiPublicWidgetAuraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workout-history': {
      id: '/_authenticated/workout-history'
      path: '/workout-history'
      fullPath: '/workout-history'
      preLoaderRoute: typeof AuthenticatedWorkoutHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/weight-history': {
      id: '/_authenticated/weight-history'
      path: '/weight-history'
      fullPath: '/weight-history'
      preLoaderRoute: typeof AuthenticatedWeightHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/weight': {
      id: '/_authenticated/weight'
      path: '/weight'
      fullPath: '/weight'
      preLoaderRoute: typeof AuthenticatedWeightRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/social': {
      id: '/_authenticated/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AuthenticatedSocialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nutrition': {
      id: '/_authenticated/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AuthenticatedNutritionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meal-planner': {
      id: '/_authenticated/meal-planner'
      path: '/meal-planner'
      fullPath: '/meal-planner'
      preLoaderRoute: typeof AuthenticatedMealPlannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fitness': {
      id: '/_authenticated/fitness'
      path: '/fitness'
      fullPath: '/fitness'
      preLoaderRoute: typeof AuthenticatedFitnessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fasting': {
      id: '/_authenticated/fasting'
      path: '/fasting'
      fullPath: '/fasting'
      preLoaderRoute: typeof AuthenticatedFastingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/badges': {
      id: '/_authenticated/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof AuthenticatedBadgesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-coach': {
      id: '/_authenticated/ai-coach'
      path: '/ai-coach'
      fullPath: '/ai-coach'
      preLoaderRoute: typeof AuthenticatedAiCoachRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity-history': {
      id: '/_authenticated/activity-history'
      path: '/activity-history'
      fullPath: '/activity-history'
      preLoaderRoute: typeof AuthenticatedActivityHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/generate-exercise-frames': {
      id: '/api/admin/generate-exercise-frames'
      path: '/api/admin/generate-exercise-frames'
      fullPath: '/api/admin/generate-exercise-frames'
      preLoaderRoute: typeof ApiAdminGenerateExerciseFramesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bootstrap-admin': {
      id: '/api/admin/bootstrap-admin'
      path: '/api/admin/bootstrap-admin'
      fullPath: '/api/admin/bootstrap-admin'
      preLoaderRoute: typeof ApiAdminBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workout-session/$templateId': {
      id: '/_authenticated/workout-session/$templateId'
      path: '/workout-session/$templateId'
      fullPath: '/workout-session/$templateId'
      preLoaderRoute: typeof AuthenticatedWorkoutSessionTemplateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-coach/$threadId': {
      id: '/_authenticated/ai-coach/$threadId'
      path: '/$threadId'
      fullPath: '/ai-coach/$threadId'
      preLoaderRoute: typeof AuthenticatedAiCoachThreadIdRouteImport
      parentRoute: typeof AuthenticatedAiCoachRoute
    }
    '/_authenticated/admin/exercise-frames': {
      id: '/_authenticated/admin/exercise-frames'
      path: '/admin/exercise-frames'
      fullPath: '/admin/exercise-frames'
      preLoaderRoute: typeof AuthenticatedAdminExerciseFramesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/edit': {
      id: '/_authenticated/admin/edit'
      path: '/admin/edit'
      fullPath: '/admin/edit'
      preLoaderRoute: typeof AuthenticatedAdminEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity-session/$activityId': {
      id: '/_authenticated/activity-session/$activityId'
      path: '/activity-session/$activityId'
      fullPath: '/activity-session/$activityId'
      preLoaderRoute: typeof AuthenticatedActivitySessionActivityIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget/aura': {
      id: '/api/public/widget/aura'
      path: '/api/public/widget/aura'
      fullPath: '/api/public/widget/aura'
      preLoaderRoute: typeof ApiPublicWidgetAuraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-reminders': {
      id: '/api/public/hooks/send-reminders'
      path: '/api/public/hooks/send-reminders'
      fullPath: '/api/public/hooks/send-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-aura-tips': {
      id: '/api/public/hooks/send-aura-tips'
      path: '/api/public/hooks/send-aura-tips'
      fullPath: '/api/public/hooks/send-aura-tips'
      preLoaderRoute: typeof ApiPublicHooksSendAuraTipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exercise-frame/$id/$i': {
      id: '/api/exercise-frame/$id/$i'
      path: '/api/exercise-frame/$id/$i'
      fullPath: '/api/exercise-frame/$id/$i'
      preLoaderRoute: typeof ApiExerciseFrameIdIRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAiCoachRouteChildren {
  AuthenticatedAiCoachThreadIdRoute: typeof AuthenticatedAiCoachThreadIdRoute
}

const AuthenticatedAiCoachRouteChildren: AuthenticatedAiCoachRouteChildren = {
  AuthenticatedAiCoachThreadIdRoute: AuthenticatedAiCoachThreadIdRoute,
}

const AuthenticatedAiCoachRouteWithChildren =
  AuthenticatedAiCoachRoute._addFileChildren(AuthenticatedAiCoachRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedActivityHistoryRoute: typeof AuthenticatedActivityHistoryRoute
  AuthenticatedAiCoachRoute: typeof AuthenticatedAiCoachRouteWithChildren
  AuthenticatedBadgesRoute: typeof AuthenticatedBadgesRoute
  AuthenticatedFastingRoute: typeof AuthenticatedFastingRoute
  AuthenticatedFitnessRoute: typeof AuthenticatedFitnessRoute
  AuthenticatedMealPlannerRoute: typeof AuthenticatedMealPlannerRoute
  AuthenticatedNutritionRoute: typeof AuthenticatedNutritionRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSocialRoute: typeof AuthenticatedSocialRoute
  AuthenticatedWeightRoute: typeof AuthenticatedWeightRoute
  AuthenticatedWeightHistoryRoute: typeof AuthenticatedWeightHistoryRoute
  AuthenticatedWorkoutHistoryRoute: typeof AuthenticatedWorkoutHistoryRoute
  AuthenticatedActivitySessionActivityIdRoute: typeof AuthenticatedActivitySessionActivityIdRoute
  AuthenticatedAdminEditRoute: typeof AuthenticatedAdminEditRoute
  AuthenticatedAdminExerciseFramesRoute: typeof AuthenticatedAdminExerciseFramesRoute
  AuthenticatedWorkoutSessionTemplateIdRoute: typeof AuthenticatedWorkoutSessionTemplateIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityHistoryRoute: AuthenticatedActivityHistoryRoute,
  AuthenticatedAiCoachRoute: AuthenticatedAiCoachRouteWithChildren,
  AuthenticatedBadgesRoute: AuthenticatedBadgesRoute,
  AuthenticatedFastingRoute: AuthenticatedFastingRoute,
  AuthenticatedFitnessRoute: AuthenticatedFitnessRoute,
  AuthenticatedMealPlannerRoute: AuthenticatedMealPlannerRoute,
  AuthenticatedNutritionRoute: AuthenticatedNutritionRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSocialRoute: AuthenticatedSocialRoute,
  AuthenticatedWeightRoute: AuthenticatedWeightRoute,
  AuthenticatedWeightHistoryRoute: AuthenticatedWeightHistoryRoute,
  AuthenticatedWorkoutHistoryRoute: AuthenticatedWorkoutHistoryRoute,
  AuthenticatedActivitySessionActivityIdRoute:
    AuthenticatedActivitySessionActivityIdRoute,
  AuthenticatedAdminEditRoute: AuthenticatedAdminEditRoute,
  AuthenticatedAdminExerciseFramesRoute: AuthenticatedAdminExerciseFramesRoute,
  AuthenticatedWorkoutSessionTemplateIdRoute:
    AuthenticatedWorkoutSessionTemplateIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  IntroRoute: IntroRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  RegisterRoute: RegisterRoute,
  WelcomeRoute: WelcomeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiAdminBootstrapAdminRoute: ApiAdminBootstrapAdminRoute,
  ApiAdminGenerateExerciseFramesRoute: ApiAdminGenerateExerciseFramesRoute,
  ApiExerciseFrameIdIRoute: ApiExerciseFrameIdIRoute,
  ApiPublicHooksSendAuraTipsRoute: ApiPublicHooksSendAuraTipsRoute,
  ApiPublicHooksSendRemindersRoute: ApiPublicHooksSendRemindersRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicWidgetAuraRoute: ApiPublicWidgetAuraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
